### ISSUE TITLE
Have a `--force` option

### ISSUE THREAD

**Issue by trimailov** [ProgrammersOfVilnius/gtimelog2jira#1]
> Script does not handle situations when timelog or Jira worklog entries are modified manualy. Script simply checks if existing Jira worklog entries does not overlap if not, then worklog entries are created. If there is an overlap, then entries are not created.

Maybe `--force` would help with issue described above? If manual changes were made - then we can just force override entries in jira?

To be fair, I am not knowledgable with jira's timelogging, thus maybe this feature is not possible at all and we must make edits manually using web UI?

**Comment by sirex** [comment]
This could be an option, but is a bit risky, because you would have to delete all overlapping issues first and then create new ones. Currently I decided to no delete anything.

**Comment by trimailov** [comment]
Sounds that it maybe a bit complicated for quick automation and manual fixes would be quicker and easier.

@sirex  - feel free to close this issue.

**Comment by mgedmin** [comment]
I added code to gtimelog2jira to print which issues contain partial overlaps; this should make it easier to know when and what you have to resolve.
